// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjXk_ECUYYtiaFiqipV61JtiYAA3Pks0',
    appId: '1:638838664523:web:5b4e1a28379b5499aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    authDomain: 'friendly-faces-29a8d.firebaseapp.com',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgDga84Pjjz9hD4960uqJYQ4UoXpeDKo',
    appId: '1:638838664523:android:9dc0110284363cc1aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSft0kgMvvGFAqr6S1OEas-bU6dCjRmU',
    appId: '1:638838664523:ios:84344e8143df8b96aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
    androidClientId: '638838664523-nltrnk4vnkomu167civolt0o1p2ob4dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.booknow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSft0kgMvvGFAqr6S1OEas-bU6dCjRmU',
    appId: '1:638838664523:ios:84344e8143df8b96aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
    androidClientId: '638838664523-nltrnk4vnkomu167civolt0o1p2ob4dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.booknow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJimFPb_e4UD1HQTqetJRpG2oU4ugYdW8',
    appId: '1:638838664523:web:1fe4908cfea8a753aeccce',
    messagingSenderId: '638838664523',
    projectId: 'friendly-faces-29a8d',
    authDomain: 'friendly-faces-29a8d.firebaseapp.com',
    storageBucket: 'friendly-faces-29a8d.appspot.com',
  );
}
